package edu.ar.uba.fi.model.apuestas;

public enum TipoBolsaApuestas {
	BOLSA_APUESTAS_GANADOR,
	BOLSA_APUESTAS_SEGUNDO,
	BOLSA_APUESTAS_TERCERO,
	BOLSA_APUESTAS_EXACTA,
	BOLSA_APUESTAS_IMPERFECTA,
	BOLSA_APUESTAS_TRIFECTA,
	BOLSA_APUESTAS_DOBLE,
	BOLSA_APUESTAS_TRIPLO,
	BOLSA_APUESTAS_CUATERNA
}
